package com.bharatkrishi.app.network

data class Current(
    val cloud: String,
    val condition: Condition,
    val dewpoint_f: String,
    val dewpoint_c: String,
    val diff_rad: String,
    val dni: String,
    val feelslike_c: Double,
    val feelslike_f: String,
    val gti: String,
    val gust_kph: String,
    val gust_mph: String,
    val heatindex_c: String,
    val heatindex_f: String,
    val humidity: Int,
    val is_day: String,
    val last_updated: String,
    val last_updated_epoch: String,
    val precip_in: String,
    val precip_mm: String,
    val pressure_in: String,
    val pressure_mb: String,
    val short_rad: String,
    val temp_c: Double,
    val temp_f: String,
    val uv: Double,
    val vis_km: String,
    val vis_miles: String,
    val wind_degree: String,
    val wind_dir: String,
    val wind_kph: Double,
    val wind_mph: String,
    val windchill_c: String,
    val windchill_f: String
)